# Generated by Django 3.2.16 on 2025-12-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_auto_20251205_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='birthday/', verbose_name='Фото'),
        ),
    ]
