# Generated by Django 3.2.16 on 2025-12-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0004_birthday_author'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='birthday',
            name='Unique person constraint',
        ),
        migrations.AddConstraint(
            model_name='birthday',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'birthday'), name='unique_person_constraint'),
        ),
    ]
